=== nightlabs/org.nightlabs.jfire.min/JFireServerManager/src/org/nightlabs/jfire/servermanager/xml/jfire-security_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="urn:jfire.org:jfire-security_1_0"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:security="urn:jfire.org:jfire-security_1_0"
>

    <xsd:complexType name="JFireSecurity">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="role" type="security:Role"></xsd:element>
    		<xsd:element name="role-group" type="security:RoleGroup"></xsd:element>
    		<xsd:element name="authority-type" type="security:AuthorityType"></xsd:element>
    	</xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="Role">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
    		<xsd:element name="name" type="security:I18nText"></xsd:element>
        	<xsd:element name="description" type="security:I18nText"></xsd:element>
    	</xsd:choice>
    	<xsd:attribute name="id" type="security:SecurityIdentifier" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="SecurityIdentifier">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[A-Za-z0-9_.#]+"></xsd:pattern>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="RoleGroup">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
        	<xsd:element name="name" type="security:I18nText"></xsd:element>
        	<xsd:element name="description" type="security:I18nText"></xsd:element>
        	<xsd:element name="role" type="security:Role"></xsd:element>
        	<xsd:element name="include-role-group" type="security:IncludeRoleGroup"></xsd:element>
        </xsd:choice>
        <xsd:attribute name="id" type="security:SecurityIdentifier" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="AuthorityType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
        	<xsd:element name="name" type="security:I18nText"></xsd:element>
        	<xsd:element name="description" type="security:I18nText">
        	</xsd:element>
        	<xsd:element name="role-group" type="security:RoleGroup"></xsd:element>
        </xsd:choice>
    	<xsd:attribute name="id" type="security:SecurityIdentifier" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="jfire-security" type="security:JFireSecurity">
    	<xsd:annotation>
    		<xsd:documentation>
    			The jfire-security element is the root element.

    			It contains the following elements:
    				- role (zero or more)
    				- role-group (zero or more)
    				- authority-type (zero or more)
    		</xsd:documentation>
    	</xsd:annotation></xsd:element>

    <xsd:complexType name="I18nText" mixed="true">
    	<xsd:attribute name="language">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:pattern value="[a-z]{2,2}"></xsd:pattern>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="IncludeRoleGroup">
    	<xsd:attribute name="id" type="security:SecurityIdentifier"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== nightlabs/org.nightlabs.jfire.min/JFireBaseBean/META-INF/jfire-security.xml
<?xml version="1.0" encoding="UTF-8"?>
<jfire-security
		xmlns="urn:jfire.org:jfire-security_1_0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="urn:jfire.org:jfire-security_1_0 https://www.jfire.org/schema/jfire-security_1_0.xsd "
>
	<role-group id="org.nightlabs.jfire.security.JFireSecurityManager#accessRightManagement">
		<name>Access right management</name>
		<name language="de">Zugriffsrechteverwaltung</name>
		<description>This right entitles the user to generally have access to the right management at all.
			Without this right, a user cannot edit any right anywhere - not even locally within an authority
			where he is granted the required rights. Note, that this right does not yet allow the user to actually
			edit anything. In order to edit access rights somewhere, it still needs the appropriate rights. This
			right can be seen as a global first door, through which a user has to go in order to get to other doors
			(of the local authorities).</description>
		<description language="de">Dieses Recht berechtigt den Benutzer zur Rechteverwaltung im allgemeinen. Ohne
			dieses Recht darf ein Benutzer keinerlei Rechte editieren - nicht einmal in einer Vollmacht, innerhalb
			der ihm die Rechteverwaltung erlaubt ist. Dieses Recht gibt dem Benutzer direkt jedoch noch keine Befugnis.
			Er benötigt zusätzlich noch die entsprechenden Rechte. Dieses Recht markiert daher sozusagen eine globale
			erste Tür, durch die der Benutzer gehen muß, um überhaupt erst in den Bereich anderer Türen (der lokalen
			Vollmachten) zu gelangen.</description>

		<role id="org.nightlabs.jfire.security.JFireSecurityManager#accessRightManagement" />
	</role-group>

	<role-group id="org.nightlabs.jfire.security.JFireSecurityManager#editAuthority">
		<name>Edit authority</name>
		<name language="de">Vollmacht bearbeiten</name>
		<description>
			With this right, the user is allowed to edit an authority.
			This includes changing the name as well as granting and
			revoking rights.
		</description>
		<description language="de">
			Mit diesem Recht wird dem Benutzer erlaubt, eine Vollmacht
			zu bearbeiten. Dies beinhaltet Änderungen am Namen ebenso
			wie die Zuteilung und Entziehung von Rechten.
		</description>

		<role id="org.nightlabs.jfire.security.JFireSecurityManager#assignAuthority">
			<name>Assign Authority to SecuredObject.</name>
			<description>
				In order to assign an Authority to a SecuredObject, the
				SecuredObject.authorityType.authority or the global
				per-organisation-authority must contain this role for
				the current user.
			</description>
		</role>
		<role id="org.nightlabs.jfire.security.JFireSecurityManager#storeAuthority" />
		<role id="org.nightlabs.jfire.security.JFireSecurityManager#setGrantedRoleGroups" />
		<role id="org.nightlabs.jfire.security.JFireSecurityManager#getRoleGroupIDSetCarrier">
			<name>get RoleGroupIDSetCarrier</name>
			<name language="de">RoleGroupIDSetCarrier holen</name>
			<description>
				This role allows getting a rolegroup configuration
			</description>
			<description language="de">
				Diese Rolle erlaubt das Lesen einer
				Rollengruppen-Konfiguration
			</description>
		</role>
	</role-group>

	<authority-type id="org.nightlabs.jfire.security.AuthorityType#organisation">
		<name></name>
		<description></description>
		<!--
			This special AuthorityType automatically has all role groups in the system. No need to configure role-groups here.
		-->
	</authority-type>

	<authority-type id="org.nightlabs.jfire.security.AuthorityType#self">
		<name></name>
		<description></description>
		<role-group id="org.nightlabs.jfire.security.JFireSecurityManager#editAuthority" />
	</authority-type>

</jfire-security>
